name: todoeey
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  retrofit: ^4.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  flutter_bloc: ^8.0.1
  mockito: ^5.4.2
  bloc_test: ^9.0.3
  flutter_modular: ^6.3.2
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.3
  formz: ^0.6.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.4.1
  json_serializable: ^6.2.0
  retrofit_generator: ^7.0.8
  flutter_native_splash: ^2.2.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/


# flutter_native_splash:
#   color: "#090E19"
#   image: assets/images/logo_splash.png
#   android_12:
#     color: "#090E19"
#     image: assets/images/logo_splash_android.png


